apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${app_name}
  namespace: ${argocd_namespace}
spec:
  project: default
  source:
    repoURL: ${repo_url}
    path: ${helm_path}
    targetRevision: ${revision}
    helm:
      parameters:
        - name: gateway.service.loadBalancerIP
          value: "${load_balancer_ip}"
  destination:
    server: https://kubernetes.default.svc
    namespace: ${app_namespace}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true